#!/usr/bin/env bash

this_dir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
cd "$this_dir"
. "$this_dir/env.sh"

if ! tmux has-session -t "$mc_server_id" &>/dev/null; then
    echo "Starting $mc_server_id"
    tmux new -d -s "$mc_server_id" "./start"
else
    echo "$mc_server_id already exists"
fi
